import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/context/Providers";
import NextTopLoader from "nextjs-toploader";
import Layout from "@/components/Layout";
import "rc-slider/assets/index.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Organic Harvest",
  description: "Generated by Organic Harvest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontClass = `${geistSans.variable} ${geistMono.variable}`;

  return (
    <html lang="en">
      <head>
        <meta name="grammarly" content="false" />
      </head>

      <body className={fontClass}>
        <NextTopLoader color="#4A7C59" />

        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
